[general]
	import = ["rose-pine.toml"]

[font]
	normal = { family = "Cascadia Code NF", style = "Light" } 
	size = 18.0

[window]
	decorations = "None"
	startup_mode = "Maximized" 
	padding = { x = 5, y = 5}
 
