unbind C-b
set -g prefix C-s
bind C-s send-prefix

set -g base-index 1
setw -g pane-base-index 1
setw -g automatic-rename on
set -g mouse on
set-option -g status-position top

set -ga terminal-overrides ",*256col*:Tc"
set -ga terminal-overrides ",xterm-257color:Tc"
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'                

# underscore colours - needs tmux-3.0                                                                                               
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'

set -g history-limit 100000


unbind %
bind | split-window -h

unbind '"'
bind - split-window -v

bind -r m resize-pane -Z


bind-key -r f run-shell "tmux neww ~/.local/scripts/tmux-sessionizer"
bind-key -r C run-shell "~/.local/scripts/tmux-sessionizer ~/.config"

bind H set-option -g status

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'MunifTanjim/tmux-mode-indicator'
set -g @plugin 'sainnhe/tmux-fzf'
set -g @plugin 'omerxx/tmux-sessionx'
set -g @plugin 'tmux-plugins/tmux-battery'

set -g @sessionx-bind 'l'
set -g @sessionx-zoxide-mode 'on'
set -g @sessionx-pointer "▶ "
set -g @sessionx-prompt " "
set -g @sessionx-window-height '50%'
set -g @sessionx-window-width '65%'
set -g @sessionx-preview-enabled 'false'
set -g @sessionx-tree-mode 'off'
set -g @sessionx-window-mode 'on'

set -g @plugin 'tmux-plugins/tmux-resurrect' # persist tmux sessions after computer restart
set -g @plugin 'tmux-plugins/tmux-continuum' # automatically saves sessions for you every 15 minutes

source ~/.config/tmux/tmux-status.conf
run '~/.config/tmux/plugins/tpm/tpm'
